# Header
menu:
  Home: /
  Archives: /archives
  TIL: categories/TIL-Today-I-Learned/
  DEV-Interviews: categories/Dev-Interview-Questions
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- category
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - archive

# widget behavior
archive_type: 'weekly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
